### ISSUE TITLE
Add an Example for TN Class

### ISSUE THREAD

**Issue by Kvasshtain** [DanWBR/dwsim5#23]
Please add an example for TN Class.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://dwsim.inforside.com.br/api_help5/html/T_DotNumerics_Optimization_TN_TN.htm

**Comment by DanWBR** [comment]
All available samples for the DotNumerics library can be found here: http://www.dotnumerics.com/NumericalLibraries/Samples/Default.aspx

I don't know how to work with this specific class as it is not used in DWSIM.

**Comment by Kvasshtain** [comment]
Thank you for your support. I'll follow your advice. Actually I've started to use Truncated Newton as it's described here: http://dwsim.inforside.com.br/api_help5/html/M_DotNumerics_Optimization_TruncatedNewton_ComputeMin.htm 26.10.2018, 14:01, "Daniel Medeiros" <notifications@github.com>:All available samples for the DotNumerics library can be found here: http://www.dotnumerics.com/NumericalLibraries/Samples/Default.aspxI don't know how to work with this specific class as it is not used in DWSIM.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by DanWBR** [comment]
I'm sorry, I thought that this was other unknown class. I do use TruncatedNewton, see here for instance: https://github.com/DanWBR/dwsim5/blob/windows/DWSIM.UnitOperations/Support%20Classes/RigorousColumnSolver.vb#L1488
