### ISSUE TITLE
Need convert FormFlowsheet.Designer.vb to UTF8

### ISSUE THREAD

**Issue by AlexanderSemenyak** [DanWBR/dwsim5#29]
Please convert file FormFlowsheet.Designer.vb to Unicode.

Cause:
1) In FormFlowSheet.vb exists field PropriedadesDasSubstânciasToolStripMenuItem with No ASCII symbols 
2) In FormFlowSheet.Designer.vb - PropriedadesDasSubstânciasToolStripMenuItem broken in other languages.

**Comment by DanWBR** [comment]
Fixed. Thanks for the report.

**Comment by AlexanderSemenyak** [comment]
Thank's :)
