### ISSUE TITLE
Error when connecting rigorous distillation column reboiler duty

### ISSUE THREAD

**Issue by alchemyst** [DanWBR/dwsim5#3]
In the attached flowsheet, connecting the "Reboiler duty" of C1 to the "C1 boil" energy stream results in the error "The requested connection between the given objects cannot be done."

I am using the MacOS version of DWsim 5.2r1, with Mono for Mac 5.10.1 downloaded from the Mono website.

![error](https://user-images.githubusercontent.com/236588/39362068-5786b43c-4a25-11e8-8089-75980b12b53a.png)

[ProfectionCols.dwxmz.zip](https://github.com/DanWBR/dwsim5/files/1955049/ProfectionCols.dwxmz.zip)

**Comment by DanWBR** [comment]
Fixed in https://github.com/DanWBR/dwsim5/commit/8397b91660a8c5fa23ffd435394d8c7713184450

The updated binaries will be out in a few days.
