### ISSUE TITLE
Add an Example for composition_types Enumeration

### ISSUE THREAD

**Issue by murtaz786** [DanWBR/dwsim5#32]
Please add an example for composition_types Enumeration.

I want to give composition values(mole fractions) for a stream in DWSim using python scripting.

Help Topic: http://dwsim.inforside.com.br/api_help57/html/T_composition_types.htm

**Comment by DanWBR** [comment]
You can use the SetOverallComposition function:

https://github.com/DanWBR/dwsim5/blob/cca225e8669bd6fcef4aa60f7c302dd3dcce84f6/DWSIM.Thermodynamics/Material%20Stream/MaterialStream.vb#L860
