### ISSUE TITLE
Error on Application Load

### ISSUE THREAD

**Issue by IbrahimOmar91** [DanWBR/dwsim5#41]
Hello,
I am having this error when the program starts after compilation

An error occurred creating the form. See Exception.InnerException for details.  The error is: The type initializer for 'CoolPropPINVOKE' threw an exception.

I am using windows 10
Visual Studio 2019
My compilation settings:
    Release WinMac
    x64

Thank You

**Comment by DanWBR** [comment]
After building a Release configuration, you must run it from the DistPackages folder, as there are some files which are copied after the build process, like the missing coolprop static library. If you prefer to copy it manually, you can find it in the PlatformFiles folder.

**Comment by IbrahimOmar91** [comment]
Thank you, that solved my problem
