### ISSUE TITLE
No mouse wheel present unhandled exception

### ISSUE THREAD

**Issue by ChaitanyaGanu** [DanWBR/dwsim5#5]
When using DWSIM on a laptop computer without a mouse attached, if you scroll down, it gives an unhandled exception that mouse wheel is not present.
It is irritating and disturbs the flow of work.

![issue](https://user-images.githubusercontent.com/28176226/39477540-35a505fc-4d7d-11e8-99df-0f3b364a4fe7.JPG)

**Comment by DanWBR** [comment]
Fixed in https://github.com/DanWBR/dwsim5/commit/6a7b97c414c2f072bd874b2cb2acc3fd2036e646

Thanks for reporting.

**Comment by ChaitanyaGanu** [comment]
Thank you so much.
