### ISSUE TITLE
Question : basic unit tests for node graph UI?

### ISSUE THREAD

**Issue by philstopford** [DanWBR/dwsim5#8]
I was really intrigued by the node graph UI built around SkiaSharp, etc. Is there a basic test application that one could more easily learn from as part of this project? It would be immensely useful to have a reference system available that others could build from.

**Comment by DanWBR** [comment]
Hi @philstopford,

You mean the code logic relative to connections, dragging, etc?

**Comment by philstopford** [comment]
Yeah - I know it's likely an imposition, but it's such a useful UI approach that a reference application showing how to use this to full effect would be a great help.

**Comment by DanWBR** [comment]
See this for a starting point: https://msdn.microsoft.com/en-us/library/ms973830.aspx. This is the equivalent project for SkiaSharp: https://github.com/DanWBR/dwsim5/tree/master/DWSIM.Drawing.SkiaSharp

Regarding the connection logic, you need to create "connecting points" in the drawing objects, which will be referenced by the connector objects. This is the code that does the connection itself: https://github.com/DanWBR/dwsim5/blob/master/DWSIM.Drawing.SkiaSharp/GraphicsSurface/DesignSurface.vb#L757

When drawing the connector, you check the referenced starting and ending points (connecting points in the two objects) and use them to draw the connector itself: https://github.com/DanWBR/dwsim5/blob/master/DWSIM.Drawing.SkiaSharp/GraphicObjects/Connector/ConnectorClass.vb#L121

Rotation, resizing, dragging, etc, all depends on the target system and are usually tied to mouse events. This is the logic for WPF: https://github.com/DanWBR/dwsim5/blob/master/DWSIM.UI.Desktop.WPF/SkiaSharp/CanvasControl.cs#L138

For GTK: https://github.com/DanWBR/dwsim5/blob/master/DWSIM.UI.Desktop.GTK/SkiaSharp/CanvasControl.cs#L122
